### ISSUE TITLE
Request: Option to not create the top and associated geometry

### ISSUE THREAD

**Issue by sIKE23** [subhero24/box-maker#1]
Many boxes that are made do not have tops. It would be very nice to have all four sides and the bottom auto generated. Thanks in advance!

**Comment by subhero24** [comment]
I needed this too, but i just generated a bigger box and cut of the top with the boolean tools.
But it would indeed be less of a hassle if the option was there. I will look into it ...

**Comment by subhero24** [comment]
Option to create open boxes has been added

**Comment by sIKE23** [comment]
Wow that was fast! Thanks for the fantastic response. Next, I thought a
toolbar button would be nice. I am starting the slow process of learning
Ruby so I did a little digging and came up with this: (didn't feel like
going though all of the rig-a-ramole to clone/fork/pull request your repo)















*  if not file_loaded?(__FILE__)   menu =
UI.menu('Plugins')   menu.add_item('BoxMaker') { self.make_box }   toolbar
= UI::Toolbar.new "Box Maker"   cmd = UI::Command.new("Create Box") {
self.make_box }     path = Sketchup.find_support_file "CreateBox.png",
"plugins/box-maker/Images/"     cmd.small_icon = path   cmd.large_icon =
path   cmd.tooltip = "Make a box! Fast! Easy!"   cmd.status_bar_text =
"This is a plugin for Sketchup which creates a 3d model of a box that can
be laser cut."   cmd.menu_text = "Create 3D Box"       toolbar =
toolbar.add_item cmd   toolbar.show   file_loaded(__FILE__)  end*

This would replace the code at lines 50 - 53 in main.rb. I also created a
quick icon for the toolbar (its attached). After I was done, I realized
that I had emulated Box.net colors unintentionally. Just a place holder as
I am not the worlds greatest graphic designer. Obviously this is your
project use it if you like or don't. Just thought that I would share.


The plugin has its own tool bar button. You can enable it via *View >
Toolbars... > Box Maker*. The toolbar button reads 'BOX':

//FC

**Comment by subhero24** [comment]
You're welcome.

Thanks for taking the time to contribute. But if you could please create that pull request though, as I can't find the icon you are referring to.

**Comment by sIKE23** [comment]
Ok, I have cloned your repo made my changes and committed them against the
master branch. Let me know if that worked or not....

//FC

**Comment by subhero24** [comment]
There is no pull request I'm afraid. You have to fork this repo so you also have a box-maker repository in your github account. Then check it out, make changes to it, commit and push to github. Then you can create the pull request ...

**Comment by sIKE23** [comment]
I do not have permissions to update your repo :( my GitHub id is sIKE23.....

**Comment by subhero24** [comment]
You do not need to update my repo. Fork this repo (not clone!) so you have the box-maker repository of your own. Then make changes to it and push to github. It is your repository then, so you have permission to do what you want. Then you can create a pull request so submit your changes to my repository.

**Comment by sIKE23** [comment]
I did this yesterday, let me know if you have any questions.

//FC
